name: package-data-example
channels:
  - conda-forge
  - selfexplainml
  - intake

dependencies:
  - python
  - pip
  - intake
  - intake-parquet
  - dask
  - pandas=1.5.3
  - panel
  - tqdm
  - hvplot
  - colorcet
  - s3fs
  - anaconda-package-data
  - python-snappy
  - jupyter
  - notebook
  - jupyter-panel-proxy
  #- condastats =0.2.1=pyh4616a5c_1
  - jq
  - gh
  - pygithub
